### ISSUE TITLE
Use more of the CDD principles on your landing page

### ISSUE THREAD

**Issue by HarrisonJackson** [smu-gui-spring-2015/nariana-sands#4]
The landing page is very clean looking, but try to use a couple more principles from our CDD class to entice the user to click.  It's also really unclear what your site actually does.  The button says click to edit - but they aren't going to click that out of the mystery of not knowing what it will actually do.

This article may help http://blog.hubspot.com/marketing/principles-of-conversion-centered-landing-page-design

**Comment by Nariana** [comment]
Re-submission!  Please check the new pull request.
